### ISSUE TITLE
Review standard operating procedure for outdated content and typos

### ISSUE THREAD

**Issue by tompollard** [CC-HIC/ccanonym#16]
The [Standard Operating Procedure](https://github.com/CC-HIC/ccanonym/blob/master/inst/SOP%20data%20release.pdf) document is clear and well structured, but some of the content appears to be outdated (particularly page 14), so a quick proofread would be beneficial. A few points to look out for are:

- Page 14, Section 7a ("Code repository for the..."). The details reported in this section do not represent the current status of the code repository. Also typo in "We recomend making..."
- Page 15, Section 7b. There is a typo in "heaptic encephalopathy". Minor thing, but might trip up people searching the document for specific diseases. This error appears in https://github.com/CC-HIC/ccanonym/blob/master/inst/anon_field_classification.CSV too, which should also be fixed.
- Page 20, Section 7d ("References"). The references are not clear and some look like they have been mangled by a reference manager (e.g. Dept of Health => Health DO). Perhaps move references out of appendix and into its own section? It would be helpful to provide a link, identifier, publication date etc to help the reader find the cited documents.

**Comment by docsteveharris** [comment]
@tompollard thanks for the this. Fixed (I think)
