### ISSUE TITLE
ccdata shares its name with another package

### ISSUE THREAD

**Issue by tompollard** [CC-HIC/ccanonym#21]
When following instructions in the [README.md](https://github.com/CC-HIC/ccanonym/blob/master/README.md), I noticed the ccdata dependency but didn't realise that this was a package developed by CC-HIC. 

After getting no results with `install.packages("ccdata")`, I Googled "ccdata R" and ended up installing [a bioinformatics package with the same name](http://bioconductor.org/packages/release/data/experiment/html/ccdata.html).

It would be helpful to clarify the installation instructions for ccdata to avoid people making the same mistake. I'm new to R, so don't know the implications of sharing names with another package. Annoying enough to warrant a name change for `ccdata`, or not?

**Comment by sinanshi** [comment]
We also found the overlap of package names in the middle of this project. As another ccdata is not on CRAN yet, we will try to submit the package with the name and see if it can go through.

**Comment by docsteveharris** [comment]
just need to beat the other ccdata to CRAN!
